services:
  mysql:
    image: mysql:latest
    env_file:
      - mysql.env
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    env_file:
      - be.env
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    image: survey-online-app:1.0.0
    ports:
      - "8880:8880"
  prometheus:
    image: prom/prometheus
    env_file:
      - prom.env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - grafana.env
    ports:
      - "3000:3000"
  mysql_exporter:
    image: prom/mysqld-exporter:latest
    volumes:
      - ./mysql_exporter/user_my.cnf:/.my.cnf
    env_file:
      - mysql.env
    expose:
      - "9104"
volumes:
  mysql-data:
