spring:
  application:
    name: SurveyApp
  datasource:
    url: ${MYSQL_ROOT}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8880

app:
  secret: ${SECRET_KEY}

security:
  allowed-ips:
    - 172.18.0.3
management:
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'prometheus'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true