global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8880']
    basic_auth:
      username: 'TestUser12'
      password: '12345678'
  - job_name: 'mysql_metrics'
    static_configs:
      - targets: ['mysql_exporter:9104']
        labels:
          alias: db1